/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MonthPickerDialog: typeof import('./src/components/MonthPickerDialog.vue')['default']
    NumberPadButton: typeof import('./src/components/NumberPadButton.vue')['default']
    NumberPadDialog: typeof import('./src/components/NumberPadDialog.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QBtnGroup: typeof import('quasar')['QBtnGroup']
    QBtnToggle: typeof import('quasar')['QBtnToggle']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QFooter: typeof import('quasar')['QFooter']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInnerLoading: typeof import('quasar')['QInnerLoading']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QRadio: typeof import('quasar')['QRadio']
    QScrollArea: typeof import('quasar')['QScrollArea']
    QSelect: typeof import('quasar')['QSelect']
    QSpace: typeof import('quasar')['QSpace']
    QSpinnerDots: typeof import('quasar')['QSpinnerDots']
    QTab: typeof import('quasar')['QTab']
    QTabPanel: typeof import('quasar')['QTabPanel']
    QTabPanels: typeof import('quasar')['QTabPanels']
    QTabs: typeof import('quasar')['QTabs']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    QTooltip: typeof import('quasar')['QTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}
