/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QBtn: typeof import('quasar')['QBtn']
    QHeader: typeof import('quasar')['QHeader']
    QInput: typeof import('quasar')['QInput']
    QLayout: typeof import('quasar')['QLayout']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
  }
}
